version: "3.7"
services:
  consul:
    image: "consul:1.7.2"
  nomad:
    image: "nomad:0.11.1"
    privileged: true
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
